#ifndef LOXC_MOD_DEMO_H
#define LOXC_MOD_DEMO_H

#include <stddef.h> /* size_t */
#include <stdint.h> /* uint32_t etc. */

#include "loxc.h"          /* loxc_module_t */
#include "loxc_stream.h"   /* writer/reader */
#include "loxc_strategy.h" /* strategy enum */

/* AUTO-GENERATED by loxc_train. DO NOT EDIT.
 * Source: trainings/demo_corpus.txt (738046 bytes)
 * Generated: 2026-05-13 17:42:28
 * Symbols: 4167, Strategy: FLAT_FIXED_WIDTH
 * Predicted compression: 89.5%
 */

#define LOXC_MOD_DEMO_ID        10
#define LOXC_MOD_DEMO_VERSION   2
#define LOXC_MOD_DEMO_STRATEGY  LOXC_STRATEGY_FLAT_FIXED_WIDTH
#define LOXC_MOD_DEMO_SYMBOLS   4167
#define LOXC_MOD_DEMO_LEVELS    0

/* Encode plain text → bit stream */
int loxc_mod_demo_encode(const char *text, size_t text_len, loxc_writer_t *w);

/* Decode bit stream → plain text */
int loxc_mod_demo_decode(loxc_reader_t *r, char *out, size_t *inout_len);

/* Register module in global registry */
int loxc_mod_demo_register(void);

#endif /* LOXC_MOD_DEMO_H */
