/* AUTO-GENERATED by loxc_train. DO NOT EDIT.
 * Source: trainings/demo_corpus.txt (738046 bytes)
 * Generated: 2026-05-14 10:49:11
 */

#include "loxc_demo.h"
#include "loxc.h"
#include "loxc_stream.h"
#include "loxc_strategy.h"
#include "loxc_hier.h"
#include "loxc_base.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define MOD_DEMO_BASE_SIZE      4u
#define MOD_DEMO_ESCAPE_POS     15u
#define MOD_DEMO_DIRECT_SLOTS   15u
#define MOD_DEMO_BITS_PER_LEVEL 4u
#define MOD_DEMO_DICT_COUNT     32u
#define MOD_DEMO_LEVELS         9u

typedef struct {
  uint8_t type;
  uint32_t byte_or_idx;
} mod_demo_symbol_t;

static const mod_demo_symbol_t mod_demo_symbols[128] = {
  { 0u, 32u },
  { 0u, 101u },
  { 0u, 116u },
  { 0u, 111u },
  { 0u, 97u },
  { 0u, 110u },
  { 0u, 105u },
  { 0u, 115u },
  { 0u, 114u },
  { 0u, 108u },
  { 0u, 104u },
  { 0u, 100u },
  { 0u, 10u },
  { 0u, 117u },
  { 0u, 109u },
  { 0u, 99u },
  { 0u, 102u },
  { 0u, 103u },
  { 0u, 121u },
  { 0u, 44u },
  { 0u, 112u },
  { 0u, 119u },
  { 0u, 98u },
  { 0u, 46u },
  { 0u, 128u },
  { 0u, 226u },
  { 0u, 118u },
  { 1u, 29u },
  { 1u, 22u },
  { 0u, 107u },
  { 0u, 73u },
  { 1u, 25u },
  { 0u, 156u },
  { 0u, 157u },
  { 1u, 30u },
  { 0u, 77u },
  { 0u, 59u },
  { 1u, 17u },
  { 1u, 27u },
  { 1u, 28u },
  { 0u, 45u },
  { 1u, 26u },
  { 1u, 24u },
  { 1u, 31u },
  { 0u, 95u },
  { 1u, 23u },
  { 1u, 21u },
  { 0u, 84u },
  { 0u, 120u },
  { 1u, 16u },
  { 0u, 76u },
  { 0u, 72u },
  { 0u, 153u },
  { 0u, 113u },
  { 1u, 2u },
  { 0u, 65u },
  { 0u, 106u },
  { 1u, 12u },
  { 1u, 20u },
  { 0u, 83u },
  { 1u, 14u },
  { 1u, 10u },
  { 1u, 19u },
  { 1u, 15u },
  { 1u, 18u },
  { 0u, 63u },
  { 1u, 13u },
  { 0u, 66u },
  { 0u, 87u },
  { 0u, 67u },
  { 1u, 9u },
  { 0u, 33u },
  { 1u, 11u },
  { 0u, 89u },
  { 0u, 74u },
  { 1u, 7u },
  { 0u, 122u },
  { 1u, 3u },
  { 0u, 58u },
  { 0u, 78u },
  { 0u, 80u },
  { 1u, 8u },
  { 1u, 6u },
  { 0u, 71u },
  { 0u, 79u },
  { 1u, 5u },
  { 0u, 91u },
  { 0u, 93u },
  { 0u, 69u },
  { 1u, 4u },
  { 0u, 82u },
  { 0u, 70u },
  { 1u, 0u },
  { 0u, 68u },
  { 1u, 1u },
  { 0u, 88u },
  { 0u, 75u },
  { 0u, 49u },
  { 0u, 52u },
  { 0u, 86u },
  { 0u, 56u },
  { 0u, 57u },
  { 0u, 50u },
  { 0u, 51u },
  { 0u, 85u },
  { 0u, 40u },
  { 0u, 41u },
  { 0u, 42u },
  { 0u, 54u },
  { 0u, 152u },
  { 0u, 53u },
  { 0u, 55u },
  { 0u, 47u },
  { 0u, 195u },
  { 0u, 48u },
  { 0u, 170u },
  { 0u, 94u },
  { 0u, 123u },
  { 0u, 125u },
  { 0u, 160u },
  { 0u, 169u },
  { 0u, 183u },
  { 0u, 194u },
  { 0u, 38u },
  { 0u, 90u },
  { 0u, 147u },
  { 0u, 162u },
  { 0u, 197u },
};

static const uint8_t mod_demo_dict_data[] = {
  0x49,0x6C,0x6C,0x75,0x73,0x74,0x72,0x61,0x74,0x69,0x6F,0x6E,
  0x43,0x61,0x74,0x68,0x65,0x72,0x69,0x6E,0x65,0x45,0x6C,0x69,
  0x7A,0x61,0x62,0x65,0x74,0x68,0x42,0x69,0x6E,0x67,0x6C,0x65,
  0x79,0x43,0x6F,0x6C,0x6C,0x69,0x6E,0x73,0x57,0x69,0x63,0x6B,
  0x68,0x61,0x6D,0x68,0x65,0x72,0x73,0x65,0x6C,0x66,0x42,0x65,
  0x6E,0x6E,0x65,0x74,0x73,0x68,0x6F,0x75,0x6C,0x64,0x44,0x61,
  0x72,0x63,0x79,0x63,0x6F,0x75,0x6C,0x64,0x74,0x68,0x65,0x69,
  0x72,0x77,0x68,0x69,0x63,0x68,0x77,0x6F,0x75,0x6C,0x64,0x62,
  0x65,0x65,0x6E,0x66,0x72,0x6F,0x6D,0x68,0x61,0x76,0x65,0x74,
  0x68,0x61,0x74,0x74,0x68,0x65,0x79,0x76,0x65,0x72,0x79,0x77,
  0x65,0x72,0x65,0x77,0x69,0x74,0x68,0x61,0x6E,0x64,0x66,0x6F,
  0x72,0x68,0x61,0x64,0x68,0x65,0x72,0x68,0x69,0x73,0x6E,0x6F,
  0x74,0x73,0x68,0x65,0x74,0x68,0x65,0x77,0x61,0x73,0x79,0x6F,
  0x75,
};

static const uint32_t mod_demo_dict_offsets[33] = {
  0u,
  12u,
  21u,
  30u,
  37u,
  44u,
  51u,
  58u,
  64u,
  70u,
  75u,
  80u,
  85u,
  90u,
  95u,
  99u,
  103u,
  107u,
  111u,
  115u,
  119u,
  123u,
  127u,
  130u,
  133u,
  136u,
  139u,
  142u,
  145u,
  148u,
  151u,
  154u,
  157u /* sentinel */
};

static const uint8_t *mod_demo_dict_entry(uint32_t idx, size_t *out_len) {
  const uint32_t start = mod_demo_dict_offsets[idx];
  const uint32_t end = mod_demo_dict_offsets[idx + 1];
  *out_len = (size_t)(end - start);
  return &mod_demo_dict_data[start];
}

static const uint32_t mod_demo_byte_to_symbol[256] = {
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x0000000Cu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x00000000u,
  0x00000047u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x0000007Bu,
  0xFFFFFFFFu,
  0x00000069u,
  0x0000006Au,
  0x0000006Bu,
  0xFFFFFFFFu,
  0x00000013u,
  0x00000028u,
  0x00000017u,
  0x00000070u,
  0x00000072u,
  0x00000061u,
  0x00000066u,
  0x00000067u,
  0x00000062u,
  0x0000006Eu,
  0x0000006Cu,
  0x0000006Fu,
  0x00000064u,
  0x00000065u,
  0x0000004Eu,
  0x00000024u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x00000041u,
  0xFFFFFFFFu,
  0x00000037u,
  0x00000043u,
  0x00000045u,
  0x0000005Du,
  0x00000058u,
  0x0000005Bu,
  0x00000053u,
  0x00000033u,
  0x0000001Eu,
  0x0000004Au,
  0x00000060u,
  0x00000032u,
  0x00000023u,
  0x0000004Fu,
  0x00000054u,
  0x00000050u,
  0xFFFFFFFFu,
  0x0000005Au,
  0x0000003Bu,
  0x0000002Fu,
  0x00000068u,
  0x00000063u,
  0x00000044u,
  0x0000005Fu,
  0x00000049u,
  0x0000007Cu,
  0x00000056u,
  0xFFFFFFFFu,
  0x00000057u,
  0x00000074u,
  0x0000002Cu,
  0xFFFFFFFFu,
  0x00000004u,
  0x00000016u,
  0x0000000Fu,
  0x0000000Bu,
  0x00000001u,
  0x00000010u,
  0x00000011u,
  0x0000000Au,
  0x00000006u,
  0x00000038u,
  0x0000001Du,
  0x00000009u,
  0x0000000Eu,
  0x00000005u,
  0x00000003u,
  0x00000014u,
  0x00000035u,
  0x00000008u,
  0x00000007u,
  0x00000002u,
  0x0000000Du,
  0x0000001Au,
  0x00000015u,
  0x00000030u,
  0x00000012u,
  0x0000004Cu,
  0x00000075u,
  0xFFFFFFFFu,
  0x00000076u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x00000018u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x0000007Du,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x0000006Du,
  0x00000034u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x00000020u,
  0x00000021u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x00000077u,
  0xFFFFFFFFu,
  0x0000007Eu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x00000078u,
  0x00000073u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x00000079u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x0000007Au,
  0x00000071u,
  0xFFFFFFFFu,
  0x0000007Fu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0x00000019u,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu,
  0xFFFFFFFFu
};

static const uint32_t mod_demo_dict_symbol_ids[32] = {
  92u,
  94u,
  54u,
  77u,
  89u,
  85u,
  82u,
  75u,
  81u,
  70u,
  61u,
  72u,
  57u,
  66u,
  60u,
  63u,
  49u,
  37u,
  64u,
  62u,
  58u,
  46u,
  28u,
  45u,
  42u,
  31u,
  41u,
  38u,
  39u,
  27u,
  34u,
  43u,
};

int loxc_mod_demo_encode(const char *text, size_t text_len, loxc_writer_t *w) {
  if (text == NULL || w == NULL) return LOXC_ERR_NULL;

  size_t i = 0;
  while (i < text_len) {
    uint32_t sym_id = 0xFFFFFFFFu;
    size_t consumed = 1;

    for (uint32_t d = 0; d < (uint32_t)MOD_DEMO_DICT_COUNT; d++) {
      size_t dlen = 0;
      const uint8_t *dbytes = mod_demo_dict_entry(d, &dlen);
      if (dlen == 0) continue;
      if (i + dlen <= text_len &&
          memcmp((const uint8_t *)text + i, dbytes, dlen) == 0) {
        sym_id = mod_demo_dict_symbol_ids[d];
        consumed = dlen;
        break;
      }
    }

    if (sym_id == 0xFFFFFFFFu) {
      sym_id = mod_demo_byte_to_symbol[(uint8_t)text[i]];
      if (sym_id == 0xFFFFFFFFu) return LOXC_ERR_SYMBOL_NOT_FOUND;
      consumed = 1;
    }

    const uint32_t level = sym_id / (uint32_t)MOD_DEMO_DIRECT_SLOTS;
    const uint32_t pos_in_level = sym_id % (uint32_t)MOD_DEMO_DIRECT_SLOTS;

    for (uint32_t l = 0; l < level; l++) {
      int rc = loxc_write_bits(w, (uint32_t)MOD_DEMO_ESCAPE_POS,
                              (uint8_t)MOD_DEMO_BITS_PER_LEVEL);
      if (rc != LOXC_OK) return rc;
    }
    {
      int rc = loxc_write_bits(w, pos_in_level,
                              (uint8_t)MOD_DEMO_BITS_PER_LEVEL);
      if (rc != LOXC_OK) return rc;
    }

    i += consumed;
  }
  return LOXC_OK;
}

int loxc_mod_demo_decode(loxc_reader_t *r, char *out, size_t *inout_len) {
  if (r == NULL || out == NULL || inout_len == NULL) return LOXC_ERR_NULL;

  size_t cap = *inout_len;
  size_t written = 0;

  for (;;) {
    if (written == cap) goto done;
    uint32_t level = 0;
    uint32_t pos = 0;
    int found = 0;

    for (level = 0; level < (uint32_t)MOD_DEMO_LEVELS; level++) {
      uint32_t val = 0;
      int rc = loxc_read_bits(r, (uint8_t)MOD_DEMO_BITS_PER_LEVEL, &val);
      if (rc != LOXC_OK) {
        if (level == 0) goto done;
        return rc;
      }
      if (val < (uint32_t)MOD_DEMO_DIRECT_SLOTS) {
        pos = val;
        found = 1;
        break;
      }
    }

    if (!found) return LOXC_ERR_INVALID_FORMAT;

    uint32_t sym_id = level * (uint32_t)MOD_DEMO_DIRECT_SLOTS + pos;
    if (sym_id >= (uint32_t)LOXC_MOD_DEMO_SYMBOLS) return LOXC_ERR_INVALID_FORMAT;

    const mod_demo_symbol_t sym = mod_demo_symbols[sym_id];
    if (sym.type == 0u) {
      if (written >= cap) { *inout_len = written; return LOXC_ERR_OVERFLOW; }
      out[written++] = (char)(uint8_t)(sym.byte_or_idx & 0xFFu);
    } else {
      size_t dlen = 0;
      const uint8_t *dbytes = mod_demo_dict_entry(sym.byte_or_idx, &dlen);
      if (written + dlen > cap) { *inout_len = written; return LOXC_ERR_OVERFLOW; }
      memcpy(out + written, dbytes, dlen);
      written += dlen;
    }
  }

done:
  *inout_len = written;
  return LOXC_OK;
}

static int mod_demo_encode_buffer(const uint8_t *in, size_t in_len, uint8_t *out,
                                size_t out_cap, size_t *out_len) {
  if (out_len == NULL) return LOXC_ERR_NULL;
  *out_len = 0;
  if (in == NULL || out == NULL) return LOXC_ERR_NULL;
  if (in_len > 0xFFFFFFFFu) return LOXC_ERR_OVERFLOW;

  loxc_writer_t w;
  int rc = loxc_writer_init(&w, out, out_cap);
  if (rc != LOXC_OK) return rc;

  loxc_header_t h;
  h.module_id = LOXC_MOD_DEMO_ID;
  h.version = 2;
  h.flags = 0;
  h.strategy_id = (uint8_t)LOXC_MOD_DEMO_STRATEGY;
  h.data_len = 0;
  h.level_count = (uint16_t)MOD_DEMO_LEVELS;
  /* reserved[0..3] = uncompressed input length (little-endian u32) */
  h.reserved[0] = (uint8_t)(in_len & 0xFFu);
  h.reserved[1] = (uint8_t)((in_len >> 8) & 0xFFu);
  h.reserved[2] = (uint8_t)((in_len >> 16) & 0xFFu);
  h.reserved[3] = (uint8_t)((in_len >> 24) & 0xFFu);
  h.crc32 = 0;

  rc = loxc_header_write(&w, &h);
  if (rc != LOXC_OK) return rc;

  rc = loxc_mod_demo_encode((const char *)in, in_len, &w);
  if (rc != LOXC_OK) return rc;
  rc = loxc_writer_flush(&w);
  if (rc != LOXC_OK) return rc;

  const size_t total = loxc_writer_size(&w);
  const size_t header_bytes = 15;
  if (total < header_bytes) return LOXC_ERR_INVALID_FORMAT;
  const size_t data_bytes = total - header_bytes;
  h.data_len = data_bytes > 0xFFFFu ? 0xFFFFu : (uint16_t)data_bytes;
  loxc_writer_t hw;
  rc = loxc_writer_init(&hw, out, header_bytes);
  if (rc != LOXC_OK) return rc;
  rc = loxc_header_write(&hw, &h);
  if (rc != LOXC_OK) return rc;
  if (loxc_writer_size(&hw) != header_bytes) return LOXC_ERR_INVALID_FORMAT;

  *out_len = total;
  return LOXC_OK;
}

static int mod_demo_decode_buffer(const uint8_t *in, size_t in_len, uint8_t *out,
                                size_t out_cap, size_t *out_len) {
  if (out_len == NULL) return LOXC_ERR_NULL;
  *out_len = 0;
  if (in == NULL || out == NULL) return LOXC_ERR_NULL;

  loxc_reader_t hr;
  int rc = loxc_reader_init(&hr, in, in_len);
  if (rc != LOXC_OK) return rc;

  loxc_header_t h;
  rc = loxc_header_read(&hr, &h);
  if (rc != LOXC_OK) return rc;
  if (h.module_id != LOXC_MOD_DEMO_ID) return LOXC_ERR_INVALID_MAGIC;
  if (h.version != 2) return LOXC_ERR_INVALID_MAGIC;
  if (h.flags != 0) return LOXC_ERR_INVALID_MAGIC;
  if (h.strategy_id != (uint8_t)LOXC_MOD_DEMO_STRATEGY) return LOXC_ERR_INVALID_MAGIC;
  if (h.level_count != (uint16_t)MOD_DEMO_LEVELS) return LOXC_ERR_INVALID_MAGIC;

  const size_t header_bytes = 15;
  if (in_len < header_bytes) return LOXC_ERR_TRUNCATED;
  size_t data_len = (size_t)h.data_len;
  if (h.data_len == 0xFFFFu) {
    data_len = in_len - header_bytes;
  } else {
    if (data_len > (in_len - header_bytes)) return LOXC_ERR_TRUNCATED;
  }

  loxc_reader_t r;
  rc = loxc_reader_init(&r, in + header_bytes, data_len);
  if (rc != LOXC_OK) return rc;

  const size_t expected_len =
      (size_t)h.reserved[0] |
      ((size_t)h.reserved[1] << 8u) |
      ((size_t)h.reserved[2] << 16u) |
      ((size_t)h.reserved[3] << 24u);
  if (expected_len > out_cap) return LOXC_ERR_OVERFLOW;
  size_t cap = expected_len;
  rc = loxc_mod_demo_decode(&r, (char *)out, &cap);
  if (rc == LOXC_ERR_OVERFLOW && cap == expected_len) {
    /* Output buffer was exactly filled; ignore trailing padding bits. */
    rc = LOXC_OK;
  }
  if (rc != LOXC_OK) return rc;
  *out_len = cap;
  return LOXC_OK;
}

static const loxc_module_t mod_demo_module = {
  .name = "demo",
  .module_id = LOXC_MOD_DEMO_ID,
  .version = LOXC_MOD_DEMO_VERSION,
  .strategy_id = LOXC_MOD_DEMO_STRATEGY,
  .encode = mod_demo_encode_buffer,
  .decode = mod_demo_decode_buffer,
};

int loxc_mod_demo_register(void) {
  return loxc_module_register(&mod_demo_module);
}
