#ifndef LOXC_MOD_ENGLISH_H
#define LOXC_MOD_ENGLISH_H

#include <stdint.h>
#include "loxc_stream.h"

/* Auto-generated by loxc_train from trainings/english.txt on May 12 2026 */

#define LOXC_MOD_ID          10
#define LOXC_MOD_VERSION     2
#define LOXC_MOD_STRATEGY    LOXC_STRATEGY_FLAT_FIXED_WIDTH
#define LOXC_MOD_SYMBOLS     4105
#define LOXC_MOD_LEVELS      0

/* Encode a single symbol to bit stream */
int loxc_mod_english_encode(uint32_t symbol_id, loxc_writer_t *w);

/* Decode a single symbol from bit stream */
int loxc_mod_english_decode(loxc_reader_t *r, uint32_t *out_symbol);

#endif /* LOXC_MOD_ENGLISH_H */
